# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="inference.proto",
    package="inference",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0finference.proto\x12\tinference"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c"\'\n\x13ImageClassification\x12\x10\n\x08taxonomy\x18\x01 \x01(\t"K\n\x10\x46\x61shionDetection\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.inference.Detection\x12\r\n\x05\x65rror\x18\x02 \x01(\t"\x81\x01\n\tDetection\x12\x10\n\x08taxonomy\x18\x01 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x02 \x01(\x02\x12\r\n\x05y_min\x18\x03 \x01(\x02\x12\r\n\x05x_min\x18\x04 \x01(\x02\x12\r\n\x05y_max\x18\x05 \x01(\x02\x12\r\n\x05x_max\x18\x06 \x01(\x02\x12\x0c\n\x04type\x18\x07 \x01(\t"6\n\x14\x46\x61shionMatchingMNIST\x12\x10\n\x08taxonomy\x18\x01 \x01(\t\x12\x0c\n\x04reco\x18\x02 \x03(\x05"%\n\x15\x46\x61shionMatchingBottom\x12\x0c\n\x04reco\x18\x01 \x03(\x05""\n\x12\x46\x61shionMatchingTop\x12\x0c\n\x04reco\x18\x01 \x03(\x05"#\n\x13\x46\x61shionMatchingFull\x12\x0c\n\x04reco\x18\x01 \x03(\x05"J\n\x16\x46\x61shionRecommendations\x12\x30\n\x0e\x66\x61shionObjects\x18\x01 \x03(\x0b\x32\x18.inference.FashionObject"/\n\rFashionObject\x12\x10\n\x08taxonomy\x18\x01 \x01(\t\x12\x0c\n\x04reco\x18\x02 \x03(\x05\x32\xe0\x04\n\x0cInferenceAPI\x12N\n\x11GetClassification\x12\x17.inference.ImageRequest\x1a\x1e.inference.ImageClassification"\x00\x12M\n\x13GetFashionDetection\x12\x17.inference.ImageRequest\x1a\x1b.inference.FashionDetection"\x00\x12U\n\x17GetFashionMatchingMNIST\x12\x17.inference.ImageRequest\x1a\x1f.inference.FashionMatchingMNIST"\x00\x12W\n\x18GetFashionMatchingBottom\x12\x17.inference.ImageRequest\x1a .inference.FashionMatchingBottom"\x00\x12Q\n\x15GetFashionMatchingTop\x12\x17.inference.ImageRequest\x1a\x1d.inference.FashionMatchingTop"\x00\x12S\n\x16GetFashionMatchingFull\x12\x17.inference.ImageRequest\x1a\x1e.inference.FashionMatchingFull"\x00\x12Y\n\x19GetFashionRecommendations\x12\x17.inference.ImageRequest\x1a!.inference.FashionRecommendations"\x00\x62\x06proto3'
    ),
)


_IMAGEREQUEST = _descriptor.Descriptor(
    name="ImageRequest",
    full_name="inference.ImageRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="image",
            full_name="inference.ImageRequest.image",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b(""),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=30,
    serialized_end=59,
)


_IMAGECLASSIFICATION = _descriptor.Descriptor(
    name="ImageClassification",
    full_name="inference.ImageClassification",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="taxonomy",
            full_name="inference.ImageClassification.taxonomy",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=61,
    serialized_end=100,
)


_FASHIONDETECTION = _descriptor.Descriptor(
    name="FashionDetection",
    full_name="inference.FashionDetection",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="detections",
            full_name="inference.FashionDetection.detections",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="error",
            full_name="inference.FashionDetection.error",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=102,
    serialized_end=177,
)


_DETECTION = _descriptor.Descriptor(
    name="Detection",
    full_name="inference.Detection",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="taxonomy",
            full_name="inference.Detection.taxonomy",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="confidence_score",
            full_name="inference.Detection.confidence_score",
            index=1,
            number=2,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="y_min",
            full_name="inference.Detection.y_min",
            index=2,
            number=3,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="x_min",
            full_name="inference.Detection.x_min",
            index=3,
            number=4,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="y_max",
            full_name="inference.Detection.y_max",
            index=4,
            number=5,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="x_max",
            full_name="inference.Detection.x_max",
            index=5,
            number=6,
            type=2,
            cpp_type=6,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="type",
            full_name="inference.Detection.type",
            index=6,
            number=7,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=180,
    serialized_end=309,
)


_FASHIONMATCHINGMNIST = _descriptor.Descriptor(
    name="FashionMatchingMNIST",
    full_name="inference.FashionMatchingMNIST",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="taxonomy",
            full_name="inference.FashionMatchingMNIST.taxonomy",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reco",
            full_name="inference.FashionMatchingMNIST.reco",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=311,
    serialized_end=365,
)


_FASHIONMATCHINGBOTTOM = _descriptor.Descriptor(
    name="FashionMatchingBottom",
    full_name="inference.FashionMatchingBottom",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="reco",
            full_name="inference.FashionMatchingBottom.reco",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=367,
    serialized_end=404,
)


_FASHIONMATCHINGTOP = _descriptor.Descriptor(
    name="FashionMatchingTop",
    full_name="inference.FashionMatchingTop",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="reco",
            full_name="inference.FashionMatchingTop.reco",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=406,
    serialized_end=440,
)


_FASHIONMATCHINGFULL = _descriptor.Descriptor(
    name="FashionMatchingFull",
    full_name="inference.FashionMatchingFull",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="reco",
            full_name="inference.FashionMatchingFull.reco",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=442,
    serialized_end=477,
)


_FASHIONRECOMMENDATIONS = _descriptor.Descriptor(
    name="FashionRecommendations",
    full_name="inference.FashionRecommendations",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="fashionObjects",
            full_name="inference.FashionRecommendations.fashionObjects",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=479,
    serialized_end=553,
)


_FASHIONOBJECT = _descriptor.Descriptor(
    name="FashionObject",
    full_name="inference.FashionObject",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="taxonomy",
            full_name="inference.FashionObject.taxonomy",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reco",
            full_name="inference.FashionObject.reco",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=555,
    serialized_end=602,
)

_FASHIONDETECTION.fields_by_name["detections"].message_type = _DETECTION
_FASHIONRECOMMENDATIONS.fields_by_name["fashionObjects"].message_type = _FASHIONOBJECT
DESCRIPTOR.message_types_by_name["ImageRequest"] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name["ImageClassification"] = _IMAGECLASSIFICATION
DESCRIPTOR.message_types_by_name["FashionDetection"] = _FASHIONDETECTION
DESCRIPTOR.message_types_by_name["Detection"] = _DETECTION
DESCRIPTOR.message_types_by_name["FashionMatchingMNIST"] = _FASHIONMATCHINGMNIST
DESCRIPTOR.message_types_by_name["FashionMatchingBottom"] = _FASHIONMATCHINGBOTTOM
DESCRIPTOR.message_types_by_name["FashionMatchingTop"] = _FASHIONMATCHINGTOP
DESCRIPTOR.message_types_by_name["FashionMatchingFull"] = _FASHIONMATCHINGFULL
DESCRIPTOR.message_types_by_name["FashionRecommendations"] = _FASHIONRECOMMENDATIONS
DESCRIPTOR.message_types_by_name["FashionObject"] = _FASHIONOBJECT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType(
    "ImageRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _IMAGEREQUEST,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.ImageRequest)
    },
)
_sym_db.RegisterMessage(ImageRequest)

ImageClassification = _reflection.GeneratedProtocolMessageType(
    "ImageClassification",
    (_message.Message,),
    {
        "DESCRIPTOR": _IMAGECLASSIFICATION,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.ImageClassification)
    },
)
_sym_db.RegisterMessage(ImageClassification)

FashionDetection = _reflection.GeneratedProtocolMessageType(
    "FashionDetection",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONDETECTION,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionDetection)
    },
)
_sym_db.RegisterMessage(FashionDetection)

Detection = _reflection.GeneratedProtocolMessageType(
    "Detection",
    (_message.Message,),
    {
        "DESCRIPTOR": _DETECTION,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.Detection)
    },
)
_sym_db.RegisterMessage(Detection)

FashionMatchingMNIST = _reflection.GeneratedProtocolMessageType(
    "FashionMatchingMNIST",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONMATCHINGMNIST,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionMatchingMNIST)
    },
)
_sym_db.RegisterMessage(FashionMatchingMNIST)

FashionMatchingBottom = _reflection.GeneratedProtocolMessageType(
    "FashionMatchingBottom",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONMATCHINGBOTTOM,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionMatchingBottom)
    },
)
_sym_db.RegisterMessage(FashionMatchingBottom)

FashionMatchingTop = _reflection.GeneratedProtocolMessageType(
    "FashionMatchingTop",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONMATCHINGTOP,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionMatchingTop)
    },
)
_sym_db.RegisterMessage(FashionMatchingTop)

FashionMatchingFull = _reflection.GeneratedProtocolMessageType(
    "FashionMatchingFull",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONMATCHINGFULL,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionMatchingFull)
    },
)
_sym_db.RegisterMessage(FashionMatchingFull)

FashionRecommendations = _reflection.GeneratedProtocolMessageType(
    "FashionRecommendations",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONRECOMMENDATIONS,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionRecommendations)
    },
)
_sym_db.RegisterMessage(FashionRecommendations)

FashionObject = _reflection.GeneratedProtocolMessageType(
    "FashionObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _FASHIONOBJECT,
        "__module__": "inference_pb2"
        # @@protoc_insertion_point(class_scope:inference.FashionObject)
    },
)
_sym_db.RegisterMessage(FashionObject)


_INFERENCEAPI = _descriptor.ServiceDescriptor(
    name="InferenceAPI",
    full_name="inference.InferenceAPI",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=605,
    serialized_end=1213,
    methods=[
        _descriptor.MethodDescriptor(
            name="GetClassification",
            full_name="inference.InferenceAPI.GetClassification",
            index=0,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_IMAGECLASSIFICATION,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionDetection",
            full_name="inference.InferenceAPI.GetFashionDetection",
            index=1,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONDETECTION,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionMatchingMNIST",
            full_name="inference.InferenceAPI.GetFashionMatchingMNIST",
            index=2,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONMATCHINGMNIST,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionMatchingBottom",
            full_name="inference.InferenceAPI.GetFashionMatchingBottom",
            index=3,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONMATCHINGBOTTOM,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionMatchingTop",
            full_name="inference.InferenceAPI.GetFashionMatchingTop",
            index=4,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONMATCHINGTOP,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionMatchingFull",
            full_name="inference.InferenceAPI.GetFashionMatchingFull",
            index=5,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONMATCHINGFULL,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="GetFashionRecommendations",
            full_name="inference.InferenceAPI.GetFashionRecommendations",
            index=6,
            containing_service=None,
            input_type=_IMAGEREQUEST,
            output_type=_FASHIONRECOMMENDATIONS,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_INFERENCEAPI)

DESCRIPTOR.services_by_name["InferenceAPI"] = _INFERENCEAPI

# @@protoc_insertion_point(module_scope)
