# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import inference_pb2 as inference__pb2


class InferenceAPIStub(object):
    """The inference api service definition.
  """

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.GetClassification = channel.unary_unary(
            "/inference.InferenceAPI/GetClassification",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.ImageClassification.FromString,
        )
        self.GetFashionDetection = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionDetection",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionDetection.FromString,
        )
        self.GetFashionMatchingMNIST = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionMatchingMNIST",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionMatchingMNIST.FromString,
        )
        self.GetFashionMatchingBottom = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionMatchingBottom",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionMatchingBottom.FromString,
        )
        self.GetFashionMatchingTop = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionMatchingTop",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionMatchingTop.FromString,
        )
        self.GetFashionMatchingFull = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionMatchingFull",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionMatchingFull.FromString,
        )
        self.GetFashionRecommendations = channel.unary_unary(
            "/inference.InferenceAPI/GetFashionRecommendations",
            request_serializer=inference__pb2.ImageRequest.SerializeToString,
            response_deserializer=inference__pb2.FashionRecommendations.FromString,
        )


class InferenceAPIServicer(object):
    """The inference api service definition.
  """

    def GetClassification(self, request, context):
        """Get classification
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionDetection(self, request, context):
        """Get fashion detection
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionMatchingMNIST(self, request, context):
        """Get fashion matching embedding for fashion-MNIST
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionMatchingBottom(self, request, context):
        """Get fashion matching embedding for dive-dataset-bottom
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionMatchingTop(self, request, context):
        """Get fashion matching embedding for dive-dataset-top
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionMatchingFull(self, request, context):
        """Get fashion matching embedding for dive-dataset-full
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFashionRecommendations(self, request, context):
        """Get fashion crop and Get the matching embedding(top/ bottom/ full)
    """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InferenceAPIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetClassification": grpc.unary_unary_rpc_method_handler(
            servicer.GetClassification,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.ImageClassification.SerializeToString,
        ),
        "GetFashionDetection": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionDetection,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionDetection.SerializeToString,
        ),
        "GetFashionMatchingMNIST": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionMatchingMNIST,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionMatchingMNIST.SerializeToString,
        ),
        "GetFashionMatchingBottom": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionMatchingBottom,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionMatchingBottom.SerializeToString,
        ),
        "GetFashionMatchingTop": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionMatchingTop,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionMatchingTop.SerializeToString,
        ),
        "GetFashionMatchingFull": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionMatchingFull,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionMatchingFull.SerializeToString,
        ),
        "GetFashionRecommendations": grpc.unary_unary_rpc_method_handler(
            servicer.GetFashionRecommendations,
            request_deserializer=inference__pb2.ImageRequest.FromString,
            response_serializer=inference__pb2.FashionRecommendations.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "inference.InferenceAPI", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
